---
title: Introduction
authors:
  - name: Eric Terry
    email: Eric_Terry@McAfee.com
layout: page
---

:page-layout: base
:toc: right
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlight.js
:mdash: &#8212;
:language: asciidoc
:source-language: {language}
:table-caption!:
:example-caption!:
:figure-caption!:
:linkattrs:

[NOTE]
.This document is under active development and discussion!
If you find errors or omissions in this document, please let us know. You can ask questions and discuss anything on Chat or Email.

Welcome to the System Integration Team's (SIT) documentation page for automated testing!  Here you will find all the information you need to get started writing tests for the SIEM, complete with concepts, examples, http://automation.ida.lab:1234/docs/screencasts/file/docs/contents.md[icon:video-camera[] screencasts^], and tips.  For detailed documentation on our gems, see:  http://automation.ida.lab:1234

.SIEM testing history
****
mailto:Matt_Hulse@McAfee.com[Matt Hulse] created the first https://www.ruby-lang.org[Ruby^] testing tool here back in 2009.  *NitroDB* was a Ruby Gem that could interact with the database.  A couple years later in 2011, he wrote *NitroAPI* in Ruby, which could call API's.  This was the beginning of automated testing in Ruby for the SIEM.

http://whiteboard.ida.lab[Whiteboard^] was born early in 2012 by mailto:Kelly_Jensen.McAfee.com[Kelly Jensen].  It's purpose initially was only for ISOing and setting up SIEM environments using the *NitroAPI* gem Matt wrote.

In Fall 2012, mailto:Thomas_Constantino@McAfee.com[Tom Constantino] (the QA Manager at the time) gave Kelly the task of creating a framework for running automated tests.  This was a high priority task and time was limited.  https://github.com/ruby/rake[Rake^], a make-like build utility for Ruby, seemed like the best tool to run these tests at the time.  A *Test Runner* was created which could run these *Rake* tests.  All of the QA department then jumped onboard to learn Ruby and start writing automation.  *Whiteboard* morphed into not only setting up environments, but now running tests against them and generating reports and emails.

Eventually a dedicated *Automation Team* was created in September 2013. Matt Hulse was chosen as the manager.  mailto:Jefferson_Dewey@McAfee.com[JT Dewey] was hired straight into this team early in 2014 as the first team member.  Kelly officially transitioned to this team shortly thereafter.  mailto:Eric_Terry@McAfee.com[Eric Terry] was the third addition, coming from the QA Department.

In January 2014 mailto:Matt_Meng.McAfee.com[Matt Meng] from the Middleware Department decided he wanted a _sexier_ testing framework for his API tests he was writing.  *M3* was born (a custom in-house testing framework). *M3* became the new standard for writing tests.  Many improvements came from *M3* and development was ongoing.

The *Automation Team* continued development on *M3* and many other testing tools.  Interns would come and go every semester, helping our team with writing tests and developing the automation frameworks and tools.

In March 2015 the *Automation Team* became the *System Integration Team* as part of our transition to Scrum.  That is when mailto:Stuart_Purser@McAfee.com[Stuart Purser], mailto:Matt_Meng.McAfee.com[Matt Meng], and mailto:Scott_Southwick@McAfee.com[Scott Southwick] came onboard, with mailto:Steven_Ridges@McAfee.com[Steve Ridges] as the new manager.

A third (and last) testing framework was agreed upon in May 2015 that would not only provide testing using API's, SQL queries, and SSH commands; but also provide testing the new GUI for the SIEM.  http://rspec.info[RSpec^] can do it all.

Later on that year Scott Southwick and Stuart Purser left our team to be with the new Release Team and mailto:David.Handy@Intel.com[Dave Handy] became the newest member.
****

=== Why write automated tests?

Those who have been in QA know well the pains and struggles that come with manual testing.  Sure the first time around is no big deal.  Test the feature.  Done.  But when it comes to releasing another version of the SIEM, and they find out they have to "sign off" on all of their "areas", it becomes a giant beast.  Now they have to redo their effort of manually testing a feature that was completed months ago.  As time goes on, their "area" expands and increases, with ever more features to manually test.  There comes a point where it is impossible to manually test all areas of the product before a release.  The technical debt of not having automated regression tests for all of those features becomes horrendous.  As a result, quality suffers and confidence in a working product goes down the drain.

This is why we need machines to do all this testing for us.  Machines are much more capable than humans at consistently testing an area of the product the same way each time, and every time.  Machines can run thousands of regression tests multiple times a day, providing everyone with confidence and trust in the product and every single commit into the code repository.  The more automation that we have, the higher the quality of our product becomes and the more time developers have for doing what they love doing.

=== Why Ruby?

TIP: Learn Ruby in less than 9 hours by going through the Ruby course at http://www.codecademy.com/tracks/ruby.  You can also try Ruby out interactively at http://tryruby.org.

"Ruby has just a deep emotional appeal of how beautiful you can write something."
-- David Heinemeier Hansson, Rails Creator David Heinemeier Hansson Explains Why He Loves Ruby, August 2, 2010

"Like most things in life, choosing the correct tool for the job needs some careful consideration and planning. Ruby makes a lot of sense for getting applications off the ground quickly and reinforcing good practices like testing, code separation, and readability that I find important in forming new digital humanities programmers."
-- Wayne Graham, Why Ruby?, May 11, 2010

"Ruby is indeed evil. So evil. Extremely evil. But why so evil? Because it's so beautiful. The syntax is so elegant, everything are objects. Everything makes sense. The Ruby-way of doing things is so sexy."
-- Simon Eskidsen, What I wish a Ruby programmer had told me one year ago, April 2010